# Generated by Django 5.2.8 on 2025-11-29 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã Năm học')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
            ],
            options={
                'verbose_name_plural': '1. Quản lý Năm học',
            },
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Mã Lớp HP')),
                ('planned_periods', models.FloatField(blank=True, null=True, verbose_name='Tổng số tiết của Lớp HP')),
                ('start_week', models.IntegerField(blank=True, null=True, verbose_name='Bắt đầu từ Tuần (nếu khác Tuần 1)')),
                ('week_count', models.IntegerField(blank=True, null=True, verbose_name='Số tuần dạy (nếu rút gọn)')),
                ('sessions_per_week', models.IntegerField(default=1, verbose_name='Số buổi/tuần dự kiến (để engine auto xếp)')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Khoá Lớp HP (không tự động thay đổi khi chạy auto xếp TKB)')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Ghi chú')),
            ],
            options={
                'verbose_name_plural': '16. Lớp học phần',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã Khoa')),
                ('name', models.CharField(max_length=100, verbose_name='Tên Khoa')),
            ],
            options={
                'verbose_name_plural': '3. Quản lý Khoa',
            },
        ),
        migrations.CreateModel(
            name='ExamBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='VD: Thi kết thúc HK1 - Đợt 1', max_length=100, verbose_name='Tên đợt thi')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Từ ngày')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Đến ngày')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Ghi chú')),
            ],
            options={
                'verbose_name_plural': '17. Đợt thi (ExamBatch)',
                'ordering': ['semester', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='InstructorRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên vai trò')),
                ('workload_reduction', models.FloatField(default=0.0, verbose_name='Tỉ lệ giảm giờ chuẩn (0.3 = giảm 30%)')),
            ],
            options={
                'verbose_name_plural': '6.1 Cấu hình Vai trò Giảng viên',
            },
        ),
        migrations.CreateModel(
            name='PeriodSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='Tiết thứ')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Giờ bắt đầu')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Giờ kết thúc')),
            ],
            options={
                'verbose_name_plural': '1.5 Cấu hình Tiết học',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Ngày nghỉ')),
                ('name', models.CharField(max_length=100, verbose_name='Tên ngày lễ')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Lặp lại hàng năm')),
            ],
            options={
                'verbose_name_plural': '1.3 Danh sách Ngày Lễ',
            },
        ),
        migrations.CreateModel(
            name='ResearchCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Mã loại NCKH')),
                ('name', models.CharField(max_length=255, verbose_name='Tên nội dung NCKH')),
                ('unit_label', models.CharField(help_text='VD: tín chỉ, bài, đề, câu hỏi...', max_length=50, verbose_name='Đơn vị tính')),
                ('default_hours_per_unit', models.FloatField(default=0, help_text='VD: 60 giờ/tín chỉ; 10 giờ/bài; 0.5 giờ/câu TN...', verbose_name='Giờ chuẩn / 1 đơn vị')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Ghi chú')),
            ],
            options={
                'verbose_name_plural': '16. Danh mục NCKH (quy đổi)',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã Loại')),
                ('name', models.CharField(max_length=100, verbose_name='Tên Loại phòng')),
            ],
            options={
                'verbose_name_plural': '9. Cấu hình Loại phòng',
            },
        ),
        migrations.CreateModel(
            name='SpecializationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã Nhóm')),
                ('name', models.CharField(max_length=100, verbose_name='Tên Nhóm chuyên môn')),
            ],
            options={
                'verbose_name_plural': '4. Cấu hình Nhóm Chuyên môn',
            },
        ),
        migrations.CreateModel(
            name='TrainingLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã Bậc')),
                ('name', models.CharField(max_length=100, verbose_name='Tên Bậc')),
                ('form', models.CharField(default='Tập trung', max_length=50, verbose_name='Hình thức')),
                ('duration_semesters', models.IntegerField(default=5, verbose_name='Số Học kỳ toàn khoá')),
            ],
            options={
                'verbose_name_plural': '2. Quản lý Bậc Đào tạo',
            },
        ),
        migrations.CreateModel(
            name='WorkloadReductionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã loại giảm')),
                ('name', models.CharField(max_length=100, verbose_name='Tên loại giảm')),
                ('teaching_reduction_percent', models.FloatField(default=0, verbose_name='Giảm ĐM GIẢNG DẠY (%)')),
                ('admin_reduction_percent', models.FloatField(default=0, verbose_name='Giảm ĐM HÀNH CHÍNH (%)')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Ghi chú')),
            ],
            options={
                'verbose_name_plural': '15.1 Danh mục Loại giảm định mức',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã GV')),
                ('name', models.CharField(max_length=100, verbose_name='Họ tên')),
                ('is_leader', models.BooleanField(default=False, verbose_name='Là Lãnh đạo (cờ tổng quát)')),
                ('teaching_quota', models.FloatField(default=415, verbose_name='Định mức GIẢNG DẠY (Tiết)')),
                ('admin_quota', models.FloatField(default=480, verbose_name='Định mức HÀNH CHÍNH (Giờ)')),
                ('conversion_ratio', models.FloatField(default=3.2, verbose_name='Hệ số quy đổi giờ chuẩn → giờ HC')),
                ('max_subjects_per_semester', models.IntegerField(default=3, verbose_name='Tối đa môn được phân dạy mỗi Học kỳ')),
                ('can_teach_general', models.BooleanField(default=False, verbose_name='Có dạy được các môn chung (đại cương)?')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.department', verbose_name='Thuộc Khoa')),
                ('roles', models.ManyToManyField(blank=True, to='timetable.instructorrole', verbose_name='Vai trò (ảnh hưởng giảm giờ chuẩn)')),
            ],
            options={
                'verbose_name_plural': '6. Quản lý Giảng viên',
            },
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField(verbose_name='Ngày thi')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Giờ bắt đầu')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Giờ kết thúc')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Ghi chú')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_sessions', to='timetable.exambatch', verbose_name='Đợt thi')),
                ('course_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='timetable.coursesection', verbose_name='Lớp học phần')),
                ('assistant_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_exam_sessions', to='timetable.instructor', verbose_name='Giám thị phụ')),
                ('main_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_exam_sessions', to='timetable.instructor', verbose_name='Giám thị chính')),
            ],
            options={
                'verbose_name_plural': '18. Ca thi (ExamSession)',
                'ordering': ['exam_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='EnterpriseInternship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.FloatField(default=0, verbose_name='Số giờ TTDN')),
                ('enterprise_name', models.CharField(max_length=255, verbose_name='Đơn vị doanh nghiệp')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.academicyear', verbose_name='Năm học')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.instructor', verbose_name='Giảng viên')),
            ],
            options={
                'verbose_name_plural': '13. Quản lý TTDN',
            },
        ),
        migrations.AddField(
            model_name='coursesection',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.instructor', verbose_name='Giảng viên chính'),
        ),
        migrations.CreateModel(
            name='InstructorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(verbose_name='Thứ (2=1 ... CN=7)')),
                ('start_period', models.IntegerField(verbose_name='Tiết bắt đầu')),
                ('end_period', models.IntegerField(verbose_name='Tiết kết thúc')),
                ('is_available', models.BooleanField(default=True, verbose_name='Có thể dạy?')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='timetable.instructor')),
            ],
            options={
                'verbose_name_plural': '6.3 Khung thời gian rảnh/bận của GV',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã Ngành')),
                ('name', models.CharField(max_length=100, verbose_name='Tên Ngành')),
                ('is_general', models.BooleanField(default=False, verbose_name="Là Nhóm Môn chung (nếu dùng như một 'ngành' môn chung)")),
                ('total_credits', models.FloatField(blank=True, default=0, null=True, verbose_name='Tổng Tín chỉ')),
                ('total_semesters', models.IntegerField(blank=True, default=0, null=True, verbose_name='Số Học kỳ')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.department', verbose_name='Khoa quản lý')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.traininglevel', verbose_name='Thuộc Bậc')),
            ],
            options={
                'verbose_name_plural': '5. Quản lý Ngành',
            },
        ),
        migrations.AddField(
            model_name='instructor',
            name='allowed_majors',
            field=models.ManyToManyField(blank=True, to='timetable.major', verbose_name='Được phân dạy cho các Ngành'),
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Tên CTĐT (tuỳ chọn, để phân biệt)')),
                ('intake_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.academicyear', verbose_name='Khoá tuyển/Năm nhập học')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.major', verbose_name='Ngành')),
            ],
            options={
                'verbose_name_plural': '5.1 Chương trình đào tạo theo Khoá',
                'unique_together': {('major', 'intake_year')},
            },
        ),
        migrations.CreateModel(
            name='MarkingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_date', models.DateField(blank=True, help_text='Thường sau ngày thi 1-2 tuần.', null=True, verbose_name='Ngày dự kiến chấm')),
                ('deadline_date', models.DateField(blank=True, null=True, verbose_name='Hạn chót nộp điểm')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Ghi chú')),
                ('exam_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marking_session', to='timetable.examsession', verbose_name='Ca thi')),
            ],
            options={
                'verbose_name_plural': '19. Phiên chấm thi (MarkingSession)',
            },
        ),
        migrations.CreateModel(
            name='MarkingDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('GK1', 'Giám khảo 1 (chính, thường là GV dạy)'), ('GK2', 'Giám khảo 2'), ('PHU', 'Cộng sự / hỗ trợ')], default='GK1', max_length=10, verbose_name='Vai trò')),
                ('hours', models.FloatField(default=0, help_text='Nếu muốn cộng giờ chấm thi vào khối lượng GV thì điền ở đây.', verbose_name='Giờ chấm quy đổi')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.instructor', verbose_name='Giảng viên')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duties', to='timetable.markingsession', verbose_name='Phiên chấm')),
            ],
            options={
                'verbose_name_plural': '20. Phân công chấm thi (MarkingDuty)',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalDevelopment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.FloatField(default=0, verbose_name='Số giờ Bồi dưỡng')),
                ('content', models.CharField(max_length=255, verbose_name='Nội dung bồi dưỡng')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.instructor', verbose_name='Giảng viên')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.academicyear', verbose_name='Năm học')),
            ],
            options={
                'verbose_name_plural': '14. Quản lý Bồi dưỡng',
            },
        ),
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=255, verbose_name='Tên đề tài / nội dung')),
                ('quantity', models.FloatField(default=1, help_text='VD: số tín chỉ, số bài báo, số câu hỏi...', verbose_name='Số lượng đơn vị')),
                ('hours', models.FloatField(default=0, editable=False, verbose_name='Tổng giờ quy đổi')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.researchcategory', verbose_name='Loại NCKH')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.academicyear')),
            ],
            options={
                'verbose_name_plural': '12. Quản lý NCKH',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã Phòng')),
                ('name', models.CharField(max_length=100, verbose_name='Tên Phòng')),
                ('capacity', models.IntegerField(default=0, verbose_name='Sức chứa tối đa')),
                ('allowed_majors', models.ManyToManyField(blank=True, to='timetable.major', verbose_name='Ưu tiên/cho phép cho các Ngành')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.roomtype', verbose_name='Loại phòng')),
            ],
            options={
                'verbose_name_plural': '10. Quản lý Phòng học',
            },
        ),
        migrations.AddField(
            model_name='examsession',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.room', verbose_name='Phòng thi'),
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Mã Học kỳ')),
                ('name', models.CharField(max_length=100, verbose_name='Tên hiển thị')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu (Tuần 1)')),
                ('weeks', models.IntegerField(blank=True, default=15, null=True, verbose_name='Tổng số tuần (không tính tuần nghỉ)')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.academicyear', verbose_name='Thuộc Năm học')),
            ],
            options={
                'verbose_name_plural': '1.1 Cấu hình Học kỳ',
                'ordering': ['start_date'],
                'unique_together': {('academic_year', 'code')},
            },
        ),
        migrations.AddField(
            model_name='exambatch',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_batches', to='timetable.semester', verbose_name='Học kỳ'),
        ),
        migrations.AddField(
            model_name='coursesection',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.semester', verbose_name='Học kỳ'),
        ),
        migrations.CreateModel(
            name='SemesterBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên kỳ nghỉ')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Từ ngày')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Đến ngày')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.semester', verbose_name='Thuộc Học kỳ')),
            ],
            options={
                'verbose_name_plural': '1.2 Cấu hình Thời gian nghỉ',
            },
        ),
        migrations.CreateModel(
            name='SemesterWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='Tuần thứ')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu tuần')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc tuần')),
                ('is_break', models.BooleanField(default=False, verbose_name='Tuần nghỉ')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_weeks', to='timetable.semester', verbose_name='Học kỳ')),
            ],
            options={
                'verbose_name_plural': '1.4 Cấu hình Tuần trong Học kỳ',
                'ordering': ['semester', 'index'],
                'unique_together': {('semester', 'index')},
            },
        ),
        migrations.CreateModel(
            name='RoomCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(choices=[(1, 'Ưu tiên 1'), (2, 'Ưu tiên 2'), (3, 'Ưu tiên 3')], default=1)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.room')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.specializationgroup')),
            ],
            options={
                'verbose_name_plural': '10.1 Khả năng chuyên môn của Phòng',
                'unique_together': {('room', 'group')},
            },
        ),
        migrations.AddField(
            model_name='room',
            name='capabilities',
            field=models.ManyToManyField(blank=True, through='timetable.RoomCapability', to='timetable.specializationgroup', verbose_name='Nhóm chuyên môn'),
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã Lớp')),
                ('name', models.CharField(max_length=100, verbose_name='Tên Lớp')),
                ('size', models.IntegerField(default=0, verbose_name='Sĩ số')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.academicyear', verbose_name='Khoá/Năm nhập học')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.department', verbose_name='Khoa quản lý')),
                ('homeroom_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.instructor', verbose_name='GVCN')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.major', verbose_name='Ngành')),
            ],
            options={
                'verbose_name_plural': '8. Quản lý Lớp Sinh viên',
            },
        ),
        migrations.AddField(
            model_name='coursesection',
            name='classes',
            field=models.ManyToManyField(related_name='course_sections', to='timetable.studentclass', verbose_name='Các Lớp sinh viên'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã Môn/Mô-đun')),
                ('name', models.CharField(max_length=200, verbose_name='Tên Môn học/Mô-đun')),
                ('subject_type', models.CharField(choices=[('TN', 'Trắc nghiệm'), ('TL', 'Tự luận'), ('TH', 'Thực hành trên máy'), ('BC', 'Báo cáo / Tiểu luận'), ('KHAC', 'Khác')], max_length=20, verbose_name='Loại môn')),
                ('total_periods', models.FloatField(verbose_name='Tổng số Tiết/Giờ')),
                ('max_class_size', models.IntegerField(default=35, verbose_name='Sĩ số tối đa/lớp HP')),
                ('is_external_managed', models.BooleanField(default=False, verbose_name='Môn do đơn vị khác xếp TKB (không xếp trong hệ thống này)')),
                ('exam_form', models.CharField(choices=[('TN', 'Trắc nghiệm'), ('TL', 'Tự luận'), ('TH', 'Thực hành trên máy'), ('BC', 'Báo cáo / Tiểu luận'), ('KHAC', 'Khác')], default='TN', max_length=10, verbose_name='Hình thức thi chính')),
                ('has_separate_marking', models.BooleanField(default=False, help_text='Mặc định chỉ bật đối với các môn thực hành trên máy.', verbose_name='Có chấm thi riêng (sau đợt thi)')),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.major', verbose_name='Ngành (nếu là môn chuyên ngành)')),
                ('managing_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.department', verbose_name='Khoa phụ trách')),
                ('required_room_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.roomtype', verbose_name='Yêu cầu Loại phòng')),
                ('specialization_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.specializationgroup', verbose_name='Yêu cầu Nhóm chuyên môn')),
            ],
            options={
                'verbose_name_plural': '7. Quản lý Môn học',
            },
        ),
        migrations.CreateModel(
            name='InstructorCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(choices=[(1, 'Ưu tiên 1'), (2, 'Ưu tiên 2'), (3, 'Ưu tiên 3')], default=1)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.instructor')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.subject')),
            ],
            options={
                'verbose_name_plural': '6.2 Khả năng giảng dạy của GV',
                'unique_together': {('instructor', 'subject')},
            },
        ),
        migrations.AddField(
            model_name='instructor',
            name='competencies',
            field=models.ManyToManyField(blank=True, through='timetable.InstructorCompetency', to='timetable.subject', verbose_name='Khả năng giảng dạy (theo Môn)'),
        ),
        migrations.AddField(
            model_name='coursesection',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.subject', verbose_name='Môn học'),
        ),
        migrations.CreateModel(
            name='AssessmentComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên thành phần')),
                ('weight', models.FloatField(verbose_name='Trọng số (%)')),
                ('form', models.CharField(choices=[('MCQ', 'Trắc nghiệm'), ('WRITTEN', 'Tự luận'), ('PRACTICE_PC', 'Thực hành trên máy'), ('REPORT', 'Báo cáo tiểu luận'), ('OTHER', 'Khác')], max_length=50, verbose_name='Hình thức đánh giá/thi')),
                ('is_final_exam', models.BooleanField(default=False, verbose_name='Là thi kết thúc học phần?')),
                ('duration_minutes', models.IntegerField(blank=True, null=True, verbose_name='Thời lượng (phút, nếu là bài thi)')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='timetable.subject', verbose_name='Môn học')),
            ],
            options={
                'verbose_name_plural': '7.2 Cấu trúc Đánh giá Môn học',
            },
        ),
        migrations.CreateModel(
            name='SubjectChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='Thứ tự Chương/Bài')),
                ('name', models.CharField(max_length=255, verbose_name='Tên Chương/Bài')),
                ('periods', models.FloatField(verbose_name='Số tiết của Chương/Bài')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='timetable.subject', verbose_name='Môn học')),
            ],
            options={
                'verbose_name_plural': '7.1 Cấu trúc Chương/Bài Môn học',
                'ordering': ['subject', 'index'],
            },
        ),
        migrations.CreateModel(
            name='TeachingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(verbose_name='Thứ (2=1 ... CN=7)')),
                ('start_period', models.IntegerField(verbose_name='Tiết bắt đầu')),
                ('end_period', models.IntegerField(verbose_name='Tiết kết thúc')),
                ('method', models.CharField(blank=True, max_length=50, verbose_name='Phương thức dạy')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Khoá Slot (không chỉnh sửa khi auto xếp lại)')),
                ('course_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='timetable.coursesection', verbose_name='Lớp học phần')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.room', verbose_name='Phòng')),
                ('weeks', models.ManyToManyField(related_name='teaching_slots', to='timetable.semesterweek', verbose_name='Các tuần học')),
            ],
            options={
                'verbose_name_plural': '19. Chi tiết Thời khoá biểu',
                'ordering': ['day_of_week', 'start_period'],
            },
        ),
        migrations.CreateModel(
            name='InstructorDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months', models.PositiveSmallIntegerField(default=10, verbose_name='Số tháng được giảm')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Ghi chú')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.academicyear', verbose_name='Năm học')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duties', to='timetable.instructor', verbose_name='Giảng viên')),
                ('reduction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.workloadreductiontype', verbose_name='Loại giảm')),
            ],
            options={
                'verbose_name_plural': '15.2 Phân công Giảm định mức GV',
            },
        ),
        migrations.CreateModel(
            name='ResearchMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CN', 'Chủ nhiệm'), ('CS', 'Cộng sự')], default='CN', max_length=2, verbose_name='Vai trò')),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='1 = Chủ nhiệm, 2 = CS1, 3 = CS2...', verbose_name='Thứ tự trong đề tài')),
                ('share_ratio', models.FloatField(default=0, help_text='VD: 0.6 = 60%. Nếu để 0 hệ thống sẽ tự chia theo quy tắc 6:4, 4:3:3, 4:2:2:2...', verbose_name='Tỷ lệ giờ được hưởng (0–1)')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_memberships', to='timetable.instructor', verbose_name='Giảng viên')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='timetable.researchproject', verbose_name='Đề tài')),
            ],
            options={
                'verbose_name_plural': '12.1 Thành viên đề tài NCKH',
                'unique_together': {('project', 'instructor')},
            },
        ),
        migrations.CreateModel(
            name='CurriculumSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_index', models.IntegerField(verbose_name='Học kỳ (trong CTĐT)')),
                ('is_optional', models.BooleanField(default=False, verbose_name='Môn tự chọn')),
                ('total_periods', models.FloatField(blank=True, null=True, verbose_name='Tổng tiết (nếu khác Subject)')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='timetable.curriculum', verbose_name='Chương trình')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.subject', verbose_name='Môn học')),
            ],
            options={
                'verbose_name_plural': '5.2 Cấu hình Môn trong CTĐT',
                'unique_together': {('curriculum', 'subject')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='coursesection',
            unique_together={('semester', 'code')},
        ),
    ]
