# Generated by Django 5.2.8 on 2025-11-30 15:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='semester_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Nhập số học kỳ: 1, 2, 3, 4, 5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Học kỳ (số)'),
        ),
    ]
