# Generated by Django 5.2.8 on 2025-11-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesection',
            name='sessions_per_week',
            field=models.IntegerField(default=1, verbose_name='Số buổi/tuần dự kiến (để engine auto xếp)'),
        ),
    ]
