# Generated by Django 5.2.8 on 2025-11-26 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_alter_coursesection_sessions_per_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên nhiệm vụ')),
                ('reduction_percent', models.FloatField(default=0, help_text='Ví dụ: 30 cho Trưởng khoa, 15 cho GVCN, 40 cho Bí thư Đoàn...', verbose_name='Giảm định mức (%)')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Ghi chú')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.academicyear', verbose_name='Năm học')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duties', to='timetable.instructor', verbose_name='Giảng viên')),
            ],
            options={
                'verbose_name_plural': '15. Nhiệm vụ & Giảm định mức GV',
                'unique_together': {('instructor', 'academic_year', 'name')},
            },
        ),
    ]
