# Generated by Django 5.2.8 on 2025-11-26 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_instructorduty'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkloadReductionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã loại giảm')),
                ('name', models.CharField(max_length=100, verbose_name='Tên loại giảm')),
                ('teaching_reduction_percent', models.FloatField(default=0, help_text='VD: 30 = giảm 30% định mức giảng dạy', verbose_name='Giảm ĐỊNH MỨC GIẢNG DẠY (%)')),
                ('admin_reduction_percent', models.FloatField(default=0, help_text='Nếu không khác nhau thì để 0 hoặc cùng với giảng dạy', verbose_name='Giảm ĐỊNH MỨC HÀNH CHÍNH (%)')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Ghi chú')),
            ],
            options={
                'verbose_name_plural': '15.1 Danh mục Loại giảm định mức',
            },
        ),
        migrations.AlterModelOptions(
            name='instructorduty',
            options={'verbose_name_plural': '15.2 Phân công Giảm định mức GV'},
        ),
        migrations.AddField(
            model_name='instructorduty',
            name='months',
            field=models.PositiveSmallIntegerField(default=10, help_text='VD: 9 tháng cho năm học; hoặc 3 tháng nếu chỉ phụ trách một thời gian', verbose_name='Số tháng được giảm'),
        ),
        migrations.AlterUniqueTogether(
            name='instructorduty',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='instructorduty',
            name='reduction_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='timetable.workloadreductiontype', verbose_name='Loại giảm'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='instructorduty',
            unique_together={('instructor', 'academic_year', 'reduction_type')},
        ),
        migrations.RemoveField(
            model_name='instructorduty',
            name='name',
        ),
        migrations.RemoveField(
            model_name='instructorduty',
            name='reduction_percent',
        ),
    ]
