# Generated by Django 5.2.8 on 2025-11-26 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_workloadreductiontype_alter_instructorduty_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Mã loại NCKH')),
                ('name', models.CharField(max_length=255, verbose_name='Tên nội dung NCKH')),
                ('unit_label', models.CharField(help_text='VD: tín chỉ, bài, đề, câu hỏi...', max_length=50, verbose_name='Đơn vị tính')),
                ('default_hours_per_unit', models.FloatField(default=0, help_text='VD: 60 giờ/tín chỉ; 10 giờ/bài; 0.5 giờ/câu TN...', verbose_name='Giờ chuẩn / 1 đơn vị')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Ghi chú')),
            ],
            options={
                'verbose_name_plural': '16. Danh mục NCKH (quy đổi)',
            },
        ),
        migrations.AddField(
            model_name='researchproject',
            name='quantity',
            field=models.FloatField(default=1, help_text='VD: số tín chỉ, số bài báo, số câu hỏi...', verbose_name='Số lượng đơn vị'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='hours',
            field=models.FloatField(default=0, help_text='Nếu để 0 và có Loại NCKH thì hệ thống tự tính = quantity * giờ/đơn vị', verbose_name='Số giờ'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.instructor'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='topic_name',
            field=models.CharField(max_length=255, verbose_name='Tên đề tài / nội dung'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.academicyear'),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.researchcategory', verbose_name='Loại NCKH'),
        ),
    ]
