# Generated by Django 5.2.8 on 2025-11-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_researchcategory_researchproject_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorduty',
            name='months',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Số tháng được giảm'),
        ),
        migrations.AlterField(
            model_name='workloadreductiontype',
            name='admin_reduction_percent',
            field=models.FloatField(default=0, verbose_name='Giảm ĐM HÀNH CHÍNH (%)'),
        ),
        migrations.AlterField(
            model_name='workloadreductiontype',
            name='teaching_reduction_percent',
            field=models.FloatField(default=0, verbose_name='Giảm ĐM GIẢNG DẠY (%)'),
        ),
    ]
