# Generated by Django 5.2.8 on 2025-11-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_alter_instructorduty_months_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='instructorduty',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='hours',
            field=models.FloatField(default=0, help_text='Nếu để 0 và có Loại NCKH thì tự tính = quantity * giờ/đơn vị', verbose_name='Số giờ'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='quantity',
            field=models.FloatField(default=1, help_text='VD: số tín chỉ, số bài, số câu hỏi...', verbose_name='Số lượng đơn vị'),
        ),
    ]
