# Generated by Django 5.2.8 on 2025-11-27 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_alter_instructorduty_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchproject',
            name='instructor',
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='hours',
            field=models.FloatField(default=0, help_text='Nếu để 0 và có Loại NCKH thì tự tính = quantity * giờ/đơn vị', verbose_name='Tổng giờ của đề tài'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='quantity',
            field=models.FloatField(default=1, help_text='VD: số tín chỉ, số bài báo, số câu hỏi...', verbose_name='Số lượng đơn vị'),
        ),
        migrations.CreateModel(
            name='ResearchMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CN', 'Chủ nhiệm'), ('CS', 'Cộng sự')], default='CN', max_length=2)),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='1 = Chủ nhiệm, 2 = Cộng sự 1, 3 = Cộng sự 2, ...', verbose_name='Thứ tự')),
                ('share_ratio', models.FloatField(default=0, help_text='0.6 = 60% giờ của đề tài; nếu để 0 hệ thống sẽ tự chia theo quy tắc.', verbose_name='Tỷ lệ tham gia')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_memberships', to='timetable.instructor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='timetable.researchproject')),
            ],
            options={
                'verbose_name_plural': '12.1 Thành viên đề tài NCKH',
                'unique_together': {('project', 'instructor')},
            },
        ),
    ]
