# Generated by Django 5.2.8 on 2025-11-27 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_remove_researchproject_instructor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchmember',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_memberships', to='timetable.instructor', verbose_name='Giảng viên'),
        ),
        migrations.AlterField(
            model_name='researchmember',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, help_text='1 = Chủ nhiệm, 2 = CS1, 3 = CS2...', verbose_name='Thứ tự trong đề tài'),
        ),
        migrations.AlterField(
            model_name='researchmember',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='timetable.researchproject', verbose_name='Đề tài'),
        ),
        migrations.AlterField(
            model_name='researchmember',
            name='role',
            field=models.CharField(choices=[('CN', 'Chủ nhiệm'), ('CS', 'Cộng sự')], default='CN', max_length=2, verbose_name='Vai trò'),
        ),
        migrations.AlterField(
            model_name='researchmember',
            name='share_ratio',
            field=models.FloatField(default=0, help_text='VD: 0.6 = 60%. Nếu để 0 hệ thống sẽ tự chia theo quy tắc 6:4, 4:3:3, 4:2:2:2...', verbose_name='Tỷ lệ giờ được hưởng (0–1)'),
        ),
    ]
