# Generated by Django 5.2.8 on 2025-11-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0009_alter_researchmember_instructor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchproject',
            name='hours',
            field=models.FloatField(default=0, editable=False, verbose_name='Tổng giờ quy đổi'),
        ),
    ]
