# Generated by Django 5.2.8 on 2025-11-27 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0010_alter_researchproject_hours'),
    ]

    operations = []
