# Generated by Django 5.2.8 on 2025-11-27 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0011_alter_examinvigilationassignment_unique_together_and_more'),
    ]

    operations = [
    ]
